### PR TITLE
Check that attributedText != nil in processLinks

### PR DESCRIPTION
**Pull request by cdzombak**
This patch comes from @KevinVitale; he made this change to prevent a crash he encountered.

### CODE REVIEW

**Comment by indragiek** [comment]
Good catch! I would prefer if the nil check was made inside `didSet()` of `attributedText`, however. Thank you.

**Comment by cdzombak** [comment]
@indragiek could you take a look at this again, please? My coworker pointed out that even if `attributedText` is `nil`, it's important that [`linkRanges` and `super.attributedText` are updated](https://github.com/cdzombak/INDLinkLabel/commit/ef134fe8c0c82d016d5e854de1743a865ed25541?w=1#diff-658690b6c1854dcd0b56c669a16d6161R159).

**Comment by indragiek** [comment]
You're correct, thank you. :boom:

**Comment by cdzombak** [comment]
Thank you!

**Pull request merged**
